BEGIN;
-- Chave da loja criada no banco e armazenada no gerador apenas como hash.
do $$
declare
  v_slug constant text := 'lets';
  v_email constant text := 'letsoculosesportivos@gmail.com';
  v_phone constant text := '5581991913135';
  v_domain constant text := 'https://provoulevou.com.br/catalogo/?loja=lets';
  v_lead constant uuid := '5eebd8e5-dbad-452d-93d1-0d4983a51c9e';
  v_key text;
begin
  if exists (select 1 from public.pl_catalog_stores where slug=v_slug) then
    raise notice 'Catálogo já cadastrado: %',v_slug;
    return;
  end if;
  if exists (select 1 from public.pl_catalog_stores where lower(owner_email)=v_email) then
    raise exception 'Este e-mail já possui catálogo; revisar identidade antes de criar';
  end if;
  if not exists (select 1 from public.leads where id=v_lead and telefone='558193227426') then
    raise exception 'Lead da Lets não confirmado';
  end if;
  v_key := encode(gen_random_bytes(32),'hex');
  insert into public.pl_catalog_stores
    (slug,display_name,logo_url,whatsapp,owner_email,plan,is_active,primary_color,tema,limite_diario,store_api_key)
  values (v_slug,'Let’s Óculos Esportivos','https://provoulevou.com.br/catalogo/assets/lets/logo.webp',v_phone,v_email,
    'basic',true,'#C53610',
    '{"bg":"#FFF8F4","card":"#FFFFFF","line":"#F0D6CA","brand":"#C53610","dark":"#9B290C","soft":"#FFE4D9","on":"#FFFFFF","cta":"#C53610","ctaDark":"#9B290C","onCta":"#FFFFFF"}'::jsonb,
    3,v_key);
  insert into public.provou_levou_stores
    (name,domain,email,company,phone,plan,status,active,api_key_hash,api_key_active,platform,categoria,store_id)
  values ('Let’s Óculos Esportivos',v_domain,v_email,'Let’s Óculos Esportivos',v_phone,'basic','Teste Gratuito',true,
    encode(digest(v_key,'sha256'),'hex'),true,'catalogo','oculos',v_slug);
  update public.leads set status='testando',email=v_email,updated_at=now(),
    teste_gratis_em=coalesce(teste_gratis_em,current_date)
    where id=v_lead;
  insert into public.crm_lead_etapas(lead_id,status) values (v_lead,'teste_catalogo_7_dias')
    on conflict (lead_id) do update set status=excluded.status,updated_at=now();
  insert into public.interacoes(lead_id,tipo,conteudo)
    select v_lead,'nota','Catálogo Lets criado; teste grátis de 7 dias iniciado.'
    where not exists (select 1 from public.interacoes where lead_id=v_lead and tipo='nota'
      and conteudo='Catálogo Lets criado; teste grátis de 7 dias iniciado.');
end $$;

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Ironman 01',179,'',true,0,'oculos','kyte-1727196508533-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727196508533-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727196508533-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196508533-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196508533-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727196508533-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Ironman 02',179,'',true,1,'oculos','kyte-1724878309078-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724878309078-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724878309078-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878309078-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878309078-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724878309078-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Ironman 03',179,'',true,2,'oculos','kyte-1727196582851-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727196582851-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727196582851-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196582851-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196582851-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727196582851-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Ironman 04',179,'',true,3,'oculos','kyte-1727196613500-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727196613500-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727196613500-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196613500-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196613500-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727196613500-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 02',169,'',true,4,'oculos','kyte-1724875764727-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724875764727-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724875764727-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724875764727-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724875764727-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724875764727-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 03',169,'',true,5,'oculos','kyte-1724875885893-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724875885893-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724875885893-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724875885893-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724875885893-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724875885893-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 05',169,'',true,6,'oculos','kyte-1724877320356-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724877320356-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724877320356-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724877320356-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724877320356-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724877320356-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 06',169,'',true,7,'oculos','kyte-1724877346121-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724877346121-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724877346121-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724877346121-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724877346121-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724877346121-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 07',169,'',true,8,'oculos','kyte-1724877375465-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724877375465-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724877375465-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724877375465-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724877375465-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724877375465-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 08',169,'',true,9,'oculos','kyte-1724877399136-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724877399136-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724877399136-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724877399136-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724877399136-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724877399136-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 09',169,'',true,10,'oculos','kyte-1724878083122-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724878083122-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724878083122-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878083122-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878083122-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724878083122-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 10',169,'',true,11,'oculos','kyte-1724878113542-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724878113542-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724878113542-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878113542-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878113542-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724878113542-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 11',169,'',true,12,'oculos','kyte-1724878139234-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724878139234-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724878139234-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878139234-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878139234-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724878139234-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 12',169,'',true,13,'oculos','kyte-1724878168542-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724878168542-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724878168542-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878168542-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878168542-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724878168542-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 13',169,'',true,14,'oculos','kyte-1724878205786-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724878205786-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724878205786-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878205786-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878205786-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724878205786-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 14',169,'',true,15,'oculos','kyte-1724878230046-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724878230046-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724878230046-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878230046-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878230046-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724878230046-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 15',169,'',true,16,'oculos','kyte-1727197012728-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727197012728-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727197012728-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727197012728-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727197012728-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727197012728-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 16',169,'',true,17,'oculos','kyte-1727197051858-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727197051858-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727197051858-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727197051858-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727197051858-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727197051858-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 17',169,'',true,18,'oculos','kyte-1727197074377-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727197074377-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727197074377-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727197074377-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727197074377-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727197074377-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Máscara 18',169,'',true,19,'oculos','kyte-1727197231887-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727197231887-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727197231887-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727197231887-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727197231887-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727197231887-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Óculos 01',169,'',true,20,'oculos','kyte-1724878350797-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724878350797-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724878350797-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878350797-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878350797-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724878350797-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Óculos 02',169,'',true,21,'oculos','kyte-1724878409455-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1724878409455-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1724878409455-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878409455-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1724878409455-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1724878409455-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Óculos 03',129,'',true,22,'oculos','kyte-1727196822965-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727196822965-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727196822965-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196822965-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196822965-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727196822965-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Óculos 05',129,'',true,23,'oculos','kyte-1727196879271-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727196879271-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727196879271-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196879271-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196879271-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727196879271-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);

INSERT INTO public.pl_catalog_products(store_id,name,price,description,is_active,position,categoria,client_request_id) SELECT id,'Óculos 08',129,'',true,24,'oculos','kyte-1727196967565-Hqn0q' FROM public.pl_catalog_stores WHERE slug='lets' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_products p WHERE p.store_id=pl_catalog_stores.id AND p.client_request_id='kyte-1727196967565-Hqn0q');
INSERT INTO public.pl_catalog_product_images(product_id,url,thumb_url,medium_url,position,is_primary) SELECT p.id,'https://provoulevou.com.br/catalogo/assets/lets/1727196967565-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196967565-Hqn0q.webp','https://provoulevou.com.br/catalogo/assets/lets/1727196967565-Hqn0q.webp',0,true FROM public.pl_catalog_products p JOIN public.pl_catalog_stores s ON s.id=p.store_id WHERE s.slug='lets' AND p.client_request_id='kyte-1727196967565-Hqn0q' AND NOT EXISTS(SELECT 1 FROM public.pl_catalog_product_images i WHERE i.product_id=p.id);
COMMIT;
